### ISSUE TITLE
MMLU Dataset 404 error?

### ISSUE THREAD

**Issue by dennis-rall** [leobeeson/llm_benchmarks#1]
I was trying the link for the MMLU dataset, but I got an 404 back

**Comment by leobeeson** [comment]
Hi @dennisrall,

Thanks for raising this issue. I just checked the link for the MMLU dataset, and it worked fine on my end, downloading `data.tar` as expected. Here are a few potential reasons why you might have encountered a 404 error:

1. **Network Issues**: There might have been a temporary network problem.
2. **Browser Cache**: Your browser might have cached an old state of the link. Try clearing your cache.
3. **Geographical Restrictions**: Some regions might have restrictions.
4. **Temporary Server Outage**: The server might have been down temporarily.
5. **Link Typo**: Ensure the URL was copied correctly.
6. **Firewall/Security Software**: Check if your local firewall or security settings are blocking the link.
7. **Institutional Restrictions**: If accessing from a corporate or institutional network, there might be blocks in place.

Could you please try the following steps to troubleshoot?
- Clear your browser cache and try the link again.
- Try accessing the link from a different browser or device.
- Verify the URL is entered correctly.

Let me know if any of these steps help or if you need further assistance.

**Comment by dennis-rall** [comment]
Thanks for the response, actually it is working now!
